from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home),
    path('login',views.login),
    path('admin_home',views.adminhome),
    path('adminteacher',views.adminteacher),
    path('admin_manage_parent',views.admin_manage_parent),
    path('admin_manage_parent_update/<id1>',views.admin_manage_parent_update),
    path('adminteacher_update/<id1>',views.adminteacher_update),
    path('adminteacher_delete/<id2>',views.adminteacher_delete),
    path('admin_manage_parent_delete/<id2>',views.admin_manage_parent_delete),
    path('student_home',views.student_home),
    path('teacher_home',views.teacher_home),
    path('parent_home',views.parent_home),
    path('admin_student/<id1>',views.admin_student),
    path('admin_student_update/<id1>',views.admin_student_update),
    path('admin_student_delete/<id2>',views.admin_student_delete),
    path('admin_manage_dept',views.admin_manage_dept),
    path('admindept_edit/<id1>',views.admindept_edit),
    path('admindept_delete/<id2>',views.admindept_delete),
    path('admin_manage_course/<id1>',views.admin_manage_course),
    path('admin_courseedit/<id4>',views.admin_courseedit),
    path('admin_announcement',views.admin_announcement),
    path('admin_anueedit/<id1>',views.admin_anueedit),
    path('admin_anudelete/<id2>',views.admin_anudelete),
    path('admin_manage_sem/<id1>',views.admin_manage_sem),
    path('admin_manage_subject/<id1>',views.admin_manage_subject),
    path('get_courses', views.get_courses, name='get_courses'),
    path('admin_viewteacher',views.admin_viewteacher),
    path('teacher_view_assignedsub',views.teacher_view_assignedsub),
    path('teacher_send_assignment/<id1>',views.teacher_send_assignment),
    path('student_viewdept_course',views.student_viewdept_course),
    path('student_view_marks/', views.student_view_marks, name='student_view_marks'),
    path('view_mark_detail/<int:assignment_id>/', views.view_assignment_mark_detail, name='view_assignment_mark_detail'),
    path('student_send_complaint',views.student_send_complaint),
    path('student_view_announcements',views.student_view_announcements),
    path('parent_view_announcement',views.parent_view_announcement),
    path('teacher_view_student',views.teacher_view_student),
    path('view_assignments/<int:student_id>/', views.view_assignments),
    # path('add_marks/<int:upload_id>/', views.add_marks, name='add_marks'),
    # path('add_marks/<id1>',views.add_marks),
    path('add_marks/<int:id1>/', views.add_marks, name='add_marks'),
    path('admin_coursedelete/<id2>',views.admin_coursedelete),
    path('admin_sem_edit/<id1>',views.admin_sem_edit),
    path('admin_sem_delete/<id2>',views.admin_sem_delete),
    path('admin_subedit/<id1>',views.admin_subedit),
    path('admin_subdelete/<id2>',views.admin_subdelete),
    path('admin_view_complaint',views.admin_view_complaint),
    path('parent_view_student',views.parent_view_student),
    path('parent_view_semester/<int:student_id>', views.parent_view_semester, name='parent_view_semester'),
    path('student_view_attendance',views.student_view_attendance),
    path('parent_view_studdets',views.parent_view_studdets,name='parent_view_studdets'),
    path('parent_view_marks/<int:sid>/',views.parent_view_marks,name='parent_view_marks'),
    path('parent_view_assignment_mark_detail/<int:assignment_id>/<int:sid>', views.parent_view_assignment_mark_detail, name='parent_view_assignment_mark_detail'),

#----------------------------Chat-Bot--------------------------------
    
    # path('chatbot/', views.chatbot, name='chatbot'),
    # path('chat/', views.chat, name='chat'),
    
    path('teacher_add_internal_marks/<int:student_id>/', views.teacher_add_internal_marks, name='teacher_add_internal_marks'),
    path('get_subjects/<int:semester_id>/', views.get_subjects, name='get_subjects'),
    path('add_internal_marks/', views.add_internal_marks, name='add_internal_marks'),
    path('teacher_view_attendance/<int:student_id>',views.teacher_view_attendance),
    path('teacher_view_all_attend',views.teacher_view_all_attend),
    path('detected/', views.detected, name='detected'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
