# Generated by Django 3.2.25 on 2025-03-22 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.CharField(max_length=150)),
                ('due_date', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_student_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=150)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_student_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('relation', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('dob', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=150)),
                ('religion', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('qualification', models.CharField(max_length=150)),
                ('aadhaar_no', models.CharField(max_length=150)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_student_app.course')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_student_app.department')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_student_app.login')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_student_app.parent')),
            ],
        ),
        migrations.CreateModel(
            name='UploadAssignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('grade', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('marks', models.CharField(max_length=150)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_student_app.assignments')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_student_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_student_app.department')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_student_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=150)),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_student_app.semester')),
            ],
        ),
        migrations.CreateModel(
            name='newAttandacess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_date', models.CharField(max_length=150)),
                ('at_status', models.CharField(max_length=150)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_student_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='InternalMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_student_app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_student_app.subject')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_student_app.department'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=150)),
                ('reply', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_student_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='AssignTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=150)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_student_app.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_student_app.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='assignments',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_student_app.subject'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_student_app.teacher'),
        ),
    ]
