# Generated by Django 3.2.25 on 2025-03-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('total_weekdays', models.IntegerField(default=0)),
            ],
        ),
    ]
