# Generated by Django 3.2.25 on 2025-03-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_student_app', '0002_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='total_weekdays',
            new_name='weekday_count',
        ),
    ]
